services:
  twitchdropsbot:
    image: ghcr.io/lemonlover221/twitchdropsbot:${TDB_TAG:-latest}
    container_name: TwitchDropsBot
    volumes:
      - ./config:/app/Configuration
      - ./logs:/app/logs
    environment:
      - INSIDE_DOCKER=true
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: Watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
    restart: unless-stopped
